name: koi-client CI

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "aliezan/koi-client"

jobs:
  amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push nextjs image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:latest
          build-args: |
            NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
            NEXT_PUBLIC_APPLICATION_URL=${{ secrets.NEXT_PUBLIC_APPLICATION_URL }}
            NEXT_PUBLIC_SOCKET_URL=${{ secrets.NEXT_PUBLIC_SOCKET_URL }}
            NEXT_PUBLIC_LARAVEL_URL=${{ secrets.NEXT_PUBLIC_LARAVEL_URL }}
            NEXT_PUBLIC_KOI_IMG_BASE_URL=${{ secrets.NEXT_PUBLIC_KOI_IMG_BASE_URL }}

      - name: Rebuild and redeploy app in Coolify
        run: |
          curl --request GET '${{ secrets.COOLIFY_DEV_WEBHOOK_URL }}' \
               --header 'Authorization: Bearer ${{ secrets.COOLIFY_WEBHOOK_TOKEN }}'
